### ISSUE TITLE
Rotorová hlava umožňující řízení roll i pitch os

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/Auto-G2#1]
Je potřeba namodelovat rotorová hlava pro Auto-G2 napodobující fungování rotorové hlavy vírníku TF-G1.

Rotorová hlava musí umožňovat změnu výchylek v osách pitch a roll.

Modely je potřeba modelovat parametricky, aby bylo možné snadno změnit jejich rozměry. Rozměry, které jsou napsané tužkou jsou jen odhadnuté. @kaklik je přeměří a upřesní. 

Na tomto obrázku je vidět, kde tyto modely budou umístěny. Půjde o nahrazení originálních dílů umístěných přímo pod rotorem.

## Díl 1
![20190310_221028~2](https://user-images.githubusercontent.com/5196729/54091668-f3680200-4382-11e9-9a86-c0401821e8c4.jpg)

První díl slouží k udržení konstantní vzdálenosti dvou dřevěných postranních částí pilonu a zároveň je v něm umístěna osa okolo které se otáčí ```Díl 2```. Tento díl je k postranním deskám přidělán pomocí dvou čtveřic šroubků.

## Díl 2
![20190310_221028~3](https://user-images.githubusercontent.com/5196729/54091567-bb13f400-4381-11e9-98b5-c4f61bab7bab.jpg)

Tento díl má být taková spojka pro 2 osy, které půjdou kolmo proti sobě. Zároveň tento díl má sloužit k centrování vrchní osy.

## Díl 3
![20190310_221032~2](https://user-images.githubusercontent.com/5196729/54091671-08dd2c00-4383-11e9-83a9-977a893bd0ee.jpg)

Třetí díl se oproti dílu ```Díl 2``` chová jako kloub v ose roll (náklon rotoru do stran). Kloub bude vytvořen M3 DIN912 šroubem, který musí mít v tomto dílu zapušťěnou hlavu. 

Délka a šířka tohoto celého dílu není rozhodující. Podstatná je délka "tunelu" pro osu rotoru. Tyto rozměry zatím budou upřesněny. Pro první návrh je jeho délka cca 20mm. Osou je M3 šroub. Na každém konci je ložisko, které musí být v tomto "tunelu" zapuštěno. 

Z každé strany tohoto dílu budou vyčnívat takové šikmé (rozbíhající se) sloupky.. Sloupky můžou začínat podstatně blíže středu tohoto dílu (než je na obrázku). Tím lze dosáhnout menšího dílu.

**Comment by roman-dvorak** [comment]
Mathieu Bresciani z Auterionu nám změřil potřebné rozměry.

![20190313_003355](https://user-images.githubusercontent.com/5196729/54271213-6212ae80-4581-11e9-92ad-ab5a2c0dd16c.jpg)

1 - 21.4mm (where your drawing shows the arrow) and 26.3mm (where it's attached to the aircraft)
2 - 4.2mm
3 - 2.5mm with a screw for plastic that has a thread length of 9mm
4 - 14.5mm
5 - 12.0mm

![20190313_003359](https://user-images.githubusercontent.com/5196729/54271222-663ecc00-4581-11e9-9387-104e37d751e7.jpg)

B1 - 7mm
B2 - I wasn't able to remove the bearing, but it's at least 3mm
B3 - 19.5mm

**Comment by kaklik** [comment]
Super :)  Přidal jsem [soubor](https://github.com/ThunderFly-aerospace/Auto-G2/blob/master/CAD/parameters.scad), do kterého jsem tyto parametry přepsal pro přímé použití v openscadu. Navíc tam jsou přidané i další tiskové parametry vyzkoušené na modelu TF-G1.

**Comment by kaklik** [comment]
Určitě bude  lepší, když všechny osy rotace budou ležet pokud možno v jedné rovině. Bylo by pak úplně nejlepší kdyby páky po táhla mohly být v úrovni osy pro pohyb roll. 

![image](https://user-images.githubusercontent.com/1194177/54398088-04817d80-46b9-11e9-8c9b-3844893e8d24.png)

Otvory pro šrouby, které použijeme jsou u kulových čepů M2. Možná maximálně M2.5. 
Taktéž i šrouby pro přichycení k překližkovým bočnicím budou M2. 

Myslím že aktuálně nakreslená hlava je podstatně vyšší, než je současná délka bowdenu od prerotátoru. bylo by tak zřejmě vhodné pouzdro pro ložiska rotoro posunout dolu a třeba jej rozdělit na dvě části. Pod osou šroubu osy roll a nad ní.  

Při skládání se stejně nejdříve přišouroubuje šroub Roll a pak se prostrčí osa rotoru pouzdrem.

**Comment by roman-dvorak** [comment]
Ano, otvory k přidělání k dřevěným nosníkům mají zmenšené díry na M2

Táhlo je v ose šroubů. (roll kloubu)

Ložiskové pouzdo je posunuto o kus níže. 

![Snímek z 2019-03-15 03-20-53](https://user-images.githubusercontent.com/5196729/54403794-a0b77e80-46d1-11e9-8804-64e50c2a0202.png)

**Comment by roman-dvorak** [comment]
Potřebné úpravy:

- Zmenšit tolerance okolo os (šroubů)
- Rozšířit díl 111_1002
- Prodloužit rameno dílu a zároveň to to rozšířit do stran (vnější vzdálenost 65). 111_1003..
- Díru pro osu (díl 111_1001) posunout více dopředu.

**Comment by kaklik** [comment]
Úchyty pro kulové klouby by zřejmě bylo lepší upravit tak, aby matice šroubu uchycujícího kloub byla zapuštěna v šestihranném otvoru z vnitřní strany páky pro táhlo. 
Při rozebírání tak matice bude z páky méně vypadávat.

**Comment by kaklik** [comment]
Hodilo by se zkontrolovat, jestli rozměry hlavy odpovídají tomuto nákresu: 

![pastedImagefile](https://user-images.githubusercontent.com/1194177/55011839-c9e7e100-4fe6-11e9-9a88-510ee3d335c1.png)

V případě úprav spodního dílu se čtyřmy šrouby pro uchycení hlavy by bylo vhodné matice těchto šroubů zapustit do stěny. Výrazně by to usnadnilo montáž.

**Comment by kaklik** [comment]
Vzdálenost mezi ložisky rotorové hlavy upravit tak, aby vycházela na  délku části šroubu bez závitu. Závit by měl končit tak, že při dotažení maticí by měla mezi šroubem a ložiskem zůstat minimální vůle.  Délka dříku šroubu je 20mm. 

Zároveň by pouzdro pro ložiska asi nemuselo být až tak masivní. Je výhodné, aby se při havárii utrhl celý rotor i s ložisky. Možná se tím ochrání serva a zbylé části pilonu.

**Comment by kaklik** [comment]
Vzdálenost mezi ložisky rotorové hlavy upravit tak, aby vycházela na  délku části šroubu bez závitu. Závit by měl končit tak, že při dotažení maticí by měla mezi šroubem a ložiskem zůstat minimální vůle.  Délka dříku šroubu je 20mm. 

Zároveň by pouzdro pro ložiska asi nemuselo být až tak masivní. Je výhodné, aby se při havárii utrhl celý rotor i s ložisky. Možná se tím ochrání serva a zbylé části pilonu.

**Comment by kaklik** [comment]
Spodní díl rotorové hlavy by bylo vhodné diagonálně vystužit tak, aby se zvýšila jeho tuhost. 
A nemohlo se stát tohle: 
![spodni_dil_hlavy](https://user-images.githubusercontent.com/1194177/55823801-cbdf9300-5b02-11e9-9e96-f65537d4419d.jpg)
