### ISSUE TITLE
Tisknutelná varianta rotorových listů

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/Auto-G2#11]
Vytvořit model tisknutelných listů.  Model listu by měl zachovávat stávající způsob montáže s tím, že výhledové může být jeden z dvojice šroubů nahrazen za střižný element. 

Výztuha listu může být realizována z uhlíkové kulatiny o průměru 1-2 mm.  Předpokládaný profil listu je [Clark Y](http://airfoiltools.com/airfoil/details?airfoil=clarky-il).

Nejproblematičtější částí konstrukce modelu listu je tvorba tištěné výztuhy. Zde je nejdále [3dlabprint](https://3dlabprint.com/). Kde jejich metoda generování výztuh je neznámá. Nicméně určitou variantu metody popisuje [toto video](https://www.youtube.com/watch?v=ENtC-d1bXdM).

**Comment by roman-dvorak** [comment]
- [x] Zkrátit délku listů - délka v parametrech je délka včetně závěsu rotoru
- [x] Zámky pro správné sesazení se setkávají s trubičkou.
- [ ]  Konstrukce zámků nefixuje sezazení listu ve směru hloubky listu a lze tak při lepení na listu vytvořit zub. 
- [x] Zmenšit rozlišení profilu listu - na cca 150
- [x] Změnit polohu těžiště v hloubce listu. Lehčí odtoková část listu a nebo přidání hmotnosti v náběžné hraně listu.

**Comment by kaklik** [comment]
- [x] Dělení listů na tiskové díly by zřejmě bylo dobré udělat tak, aby výsledné části byly pokud možno stejně dlouhé. Optimalizuje se tím doba tisku. 
- [x] Tisková sestava by měla obsahovat díly na dva tištěné listy zároveň zrcadlově otočené. Tím se zhomogenní případné různé hustoty filamentu. 
- [x] Tisková sestava může mít podstatně menší rozestup mezi jednotlivými díly, třeba poloviční než je teď.  Při tisku dvojice listů je navíc možné je složit odtokokovými hranami k sobě, tím se dosáhne minimalizace délky přejezdů mezi jednotlivými částmi modelu.

**Comment by kaklik** [comment]
Je potíž s tiskem tenkých stěn. Navíc model obsahuje v místech dělení některé artefakty žeber a vzájemného spojení listů.

**Comment by roman-dvorak** [comment]
Do modelu je potřeba namodelovat nové, výstuhy, které budou vyztuhovat jednotlivé dráty a plášť. Vytvořit hustější infill v okolí kořenu listu.

Dále by bylo vhodné v modelu mít pár otvorů pro vpravení lepidla v průběhu dílu.

**Comment by kaklik** [comment]
Poslední vytištěné kusy vykazují značnou nekonzistenci tvaru odtokové hrany. 

![image](https://user-images.githubusercontent.com/1194177/66061359-9a8ad180-e53f-11e9-89dc-9a2610b05bf7.png)


Zřejmě je potřeba, aby model neměl odtokovou hranu až do nulové tloušťky, ale končil třeba na tloušťce 0,4-0,6mm což by mělo odpovídat minimální šířce extruze. 

Dále by bylo vhodné, aby přídavná žebra v náběžné hraně dosahovala až i třetí uhlíkové tyčky a nokončila před ní.

**Comment by roman-dvorak** [comment]
Když máme tyto relativně funkční listy (hlavně známe správnou polohu závaží, tak navrhuji to přepracovat do té varianty tenkých stěn. Resp. plně vyplněného listu s mezerami tvořící infill. 

Asi by pro to bylo vhodné založit nové issue a detailněji to popsat. To by totiž mohl být docela pokrok v tisku a jejich kvalitě

**Comment by kaklik** [comment]
Taktéž by asi bylo vhodné zkusit použít symetrický profil.  Je pravděpodobné, že by to vedlo ke snížení intenzity vibrací.

**Comment by kaklik** [comment]
Aktuálně vytištěné modely mají tyto vady: 

- [x] Těžko se odstraňuje brim - lepší by bylo listy připevnit k podložce materiálem, který zůstane součástí listu. 
- [x] Špatně se zarovnávají tyčky do konce listu, neboť konec listu je úplně průchozí. Zde by se hodil jen malý otvor na odvzdušnění při dávkování lepidla
- [ ] Lepidlo se špatně dostává do otvorů pro tyčky, zde by bylo asi vhodné, kdyby tištěná trubička měla nějaký buď oválný tvar a nebo zde byly odvzdušňovací otvory skrz které se vymáčkne vzduch při dávkování lepidla.

**Comment by kaklik** [comment]
Na vyrobených listech jsou tyto nové problémy: 
- Zakončení otvoru pro vyztužovací drát lze snadno prorazit
- Lepidlo se stále velmi špatně nanáší na nosníky. Problematické je to zejména v kořenové části. 


V případě kořenové části by zřejmě bylo vhodné, aby list byl půlený a byla tak větší kontrola nad nanesením lepidla na celou plochu nosníku.
