### ISSUE TITLE
Vyvážení rotorových listů

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/Auto-G2#12]
Je potřeba, aby těžiště listu bylo v 25% hloubky listu. Tím bude minimalizováno kroucení listu v průběhu otáčky.

Tisknutelné rotorové listy by zřejmě bylo vhodné překonstruovat tak, aby v náběžné hraně bylo wolframové válcové závaží, pak hlouběji v listu mosazný drát fungující jako nosník a částečně jako závaží.  Symetricky oprotiti těžišti musí být výztuha naopak s malou hmotností, nejspíše uhlíková.

**Comment by kaklik** [comment]
- Prvním výsledkem výpočtu má být zjištění, zda je možné list vyvážit za použití pouze mosazných závaží.  A nebo je potřeba použít hustší materiál například [wolfrmamové elektrody](https://svareci-technika-breclav.cz/eshop/prislusenstvi-stroju/tig2012-11-05-09-28-30_/spotrebni-dily2012-11-05-09-28-59_/wolframova-elektroda-zelena-detail).
- Dále je pak potřeba zjistit optimální geometrické rozložení závaží a jejich průměry
- Následně je podle toho potřeba upravit model z issue #11

**Comment by roman-dvorak** [comment]
Napsal jsem stručný návod, jak počítat celkové těžiště rotorového listu. 
[Wiki: Vyvážení rotorových listů](https://github.com/ThunderFly-aerospace/Auto-G2/wiki/Vyv%C3%A1%C5%BEen%C3%AD-rotorov%C3%BDch-list%C5%AF)

**Comment by roman-dvorak** [comment]
Zjistlil jsem, že v modelu rotorového listu byla chyba, která způsobovala vždy konstantní tloušťku (1 mm) vnějšího pláště a parametr, který k nastavení této hodnoty má sloužit nefungovat. Tento problém jsem opravil. A je tedy možné, že když bude stěna listu tenčí, že bude možné použít pouze jeden mosazný drát nebo dva umístěné okolo osy závěsu.

Je však třeba toto ověřit výpočtem těžišt.

**Comment by kaklik** [comment]
Současná poloha těžiště od náběžné hrany listu je 11,47 mm. což je pro aktuální použití dostatečné.
