### ISSUE TITLE
Vypouštěcí zařízení pro vírník TF:Auto-g2 z lana

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/Auto-G2#15]
Protože se start z lana osvědčil jak s vírníkem TF:Auto-G2 tak i s vírníkum TF-G1, tak je potřeba nakreslit vypouštěcí zařízení pro start. 

Zařízení by mělo vypadat nějak takto:
![20190603_185109](https://user-images.githubusercontent.com/5196729/58820361-b3878280-8632-11e9-814d-c4449c633905.jpg)

Bude to taková "kostka", skrze kterou bude prostrčen M3 šroub (nebo jiná osa). V zadní části bude přiděláno servo, který bude vytahovat ocelový drát zajišťující lano oproti ose (M3 šroubu). 

V modelu musí jít nastavovat vzájemná poloha serva a hlavní kostky (ve dvou osách), kde bude docházet k odpojování lana. Dále musí jít nastavovat rozměr kostky, tloušťka stěn a spodni spojovací části. Výška sloupků a rozteče děr pro přidělání serva. Délka celého dílu by neměla přesáhnout cca 5 cm. Kostka může být dlouhá cca 2 cm,

**Comment by alcamrkvicka** [comment]
Vypouštěcí zařízení ( 888_1010 ) je přesně podle zadání hotové. 
Jen je potřeba případně upravit parametry serva a jeho držáku respektive sloupků k jeho držení.
![vypousteci zar](https://user-images.githubusercontent.com/51204144/59192395-8f6ff800-8b82-11e9-9490-bbe45c1e2f72.PNG)

**Comment by roman-dvorak** [comment]
![64297652_2460635970614821_3844892678005194752_n](https://user-images.githubusercontent.com/5196729/59224336-72611680-8bce-11e9-8fbc-6a0e3925c458.jpg)

**Comment by kaklik** [comment]
Držák je potřeba upravit tak, aby servo mělo u páky minimálně o polovinu více místa na výšku. 

![servo1](https://user-images.githubusercontent.com/1194177/59231558-66328480-8be1-11e9-801f-57a3259e6abd.JPG)
![servo2](https://user-images.githubusercontent.com/1194177/59231563-6c286580-8be1-11e9-9c0a-006d1b9d7dbf.JPG)

**Comment by alcamrkvicka** [comment]
Výška sloupků zvětšena, jsou 2 možnosti: buď 1/2 nebo 2/3 výšky serva.
A taky jsem posunula celý držák  víc excentricky.
![drzak](https://user-images.githubusercontent.com/51204144/59299314-a6027600-8c8c-11e9-8a9c-672d4205304c.PNG)

**Comment by roman-dvorak** [comment]
@kaklik nechceme, aby to servo bylo ještě dál? Nebo to je takle OK? Protože předpokládám, že tam bude ještě nějaká ta koncovka táhla a ta má také alespoň 2 cm..

**Comment by kaklik** [comment]
To taky trochu záleží na tom, jak to na ten vírník plánuješ namontovat. Ale myslím že to klidně může být celý delší.

**Comment by roman-dvorak** [comment]
můj předpoklad je to nalepit tavným lepidlem zespodu.

**Comment by roman-dvorak** [comment]
Vypouštěcí zařízení se jeví jako funkční. Bylo provedeno několik testů na zemi i odpoutání ve vzduchu. Rozsah serva byl omezen pomocí mixeru. Odpojovací zařízení bylo připojeno k AUX výstupu. Odpojovací kanál je namixován ze dvou přepínačů. Za letu je to velmi nepraktické, protože i jeden z nich je náročné obsluhovat. Možná by stálo za to zkusit jinou kombinaci vypínačů. 

Při vypnutém přepínaci je zablokované roztočení motoru - resp. Výstup z vysílačky je nulový.

Předletový test odpojovacího zařízení  https://youtu.be/7BKLIAm5EnU

**Comment by roman-dvorak** [comment]
Díry pro přidělání serva jsou daleko od sebe. Jejich vzdálenost má být 28 mm. 

Z důvodů hmotnosti a menšího motoru (menší magnetické rušení) jsme chtěli dát jiné servo. Servo na sobě němělo celé drážky (jako původní servo) ale jen díry na šroub, které nesedí s dírou ve vypouštěcím zařízení. Servo bylo prozatím propilováno.

![20190629_194912](https://user-images.githubusercontent.com/5196729/60393534-31965680-9b17-11e9-8c82-05d7feb2ab88.jpg)


Také bych o trošku zesílil spodní stěnu. Např o 0.5 mm

**Comment by roman-dvorak** [comment]
Díl by bylo vhodné rozdělit na 2 části. Na část se servem a část kostky s osičkou. Cílem toho je, aby bylo možné odebrat přední podvozek vírníku bez nutnosti se to snažit odlepit.
