### ISSUE TITLE
Tisknutelné kolečko pro přední podvozek

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/Auto-G2#16]
Modelářská kolečka jsou na podvozkovém drátu dost vyklající se. Jako možné řešení se jeví kolečka vytisknout a dát na ně nějaké gumové O-kroužky

**Comment by kaklik** [comment]
Současný návrh kolečka je vyhovující.

**Comment by roman-dvorak** [comment]
Při renderování kolečka vzniká tato chyba: 

DEPRECATED: The assign() module will be removed in future releases. Use a regular assignment instead. in file 888_1011.scad, line 414
WARNING: Too many unnamed arguments supplied, in file 888_1011.scad, line 430
ECHO: "Spiral Style..."
DEPRECATED: Using ranges of the form [begin:end] with begin value greater than t

**Comment by kaklik** [comment]
Kolečka vytištěná z PLA vyhovují.  PET-G praská.
