### ISSUE TITLE
Zlepšit možnost utržení listu

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/Auto-G2#17]
V [unašeči rotorových listů](https://github.com/ThunderFly-aerospace/Auto-G2/blob/master/CAD/STL/888_1001.stl) by bylo potřeba vytvořit zářezy z boku. Které definují místo, kde se list má ulomit při havárii. 

Představuji si, že utržení listu by mělo proběhnout v místě napojení na středový kruh. Na obrázku vyznačeno červenou barvou.  Puntíky označují místa ztečení, které se dají vytvořit například odečtením válců. 

![888_1001](https://user-images.githubusercontent.com/1194177/60547477-16e2fe00-9d20-11e9-9855-a28a3d85227d.png)

**Comment by alcamrkvicka** [comment]
Pochopila jsem to nejspis trochu jinak, ale taky by to mohlo fungovat, ne?
![image](https://user-images.githubusercontent.com/51204144/60613538-603c5780-9dcb-11e9-9b47-9916dc623294.png)

**Comment by kaklik** [comment]
Jo to tohle je úplně správně. :)

Teď jen potřebujeme vytvořit sadu takových destiček s různě velkým vykousnutím. Protože zatím nevím, jak velké vykousnutí bude správně pevné.

**Comment by kaklik** [comment]
Úprava pomohla a stačí i ten úplně nejmenší z řady otvorů. :)
