### ISSUE TITLE
Přidělat rolničku na roztáčení rotoru pomocí provázku

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/Auto-G2#21]
Na matici pro připevňení rotoru udělat rolničku, na který se namotá provázek a bude tak možné roztáčet rotor.

**Comment by kaklik** [comment]
Rotor se ale točí na druhou stranu, než se utahuje ten šroub.. 

Celkově si myslim, že to není moc dobrej nápad, protože vírník není za co chytit, když se za tu tkaničku bude tahat. 

Navrhuju to nahradit akušroubovákem. Tohle řešení jsme přece už vymýšleli.

**Comment by roman-dvorak** [comment]
Toho, že by se to povolilo s pojistnou maticí se nebojím. Rotor se sám o sobě otáčí lehce. Vírník lze obtížně chytit za tělo. Řešení s akušroubovákem se moc tehdy neosvedčilo. Ale zřejmě by se to řešení mohlo vylepšit.

**Comment by kaklik** [comment]
Ten akušroubovák co vim tak nebyl potřeba. Protože se to roztáčelo samo..  To je ostatně i ideální stav startovat za mírnýho protivětru. 

Nepamatuju si na případ, kdy se to neosvědčilo.

**Comment by kaklik** [comment]
Myslím že tohle by mělo být vyřešeno bud akuvrtačkou, nebo  prerotátorem.
