### ISSUE TITLE
Překreslit držák zadního podvozkového kolečka

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/Auto-G2#22]
![37320](https://user-images.githubusercontent.com/1194177/74817663-8f252080-52fd-11ea-8c05-515bfb0fcfe8.jpg)

https://hobbyking.com/en_us/duraflytm-auto-g2-gyrocopter-821mm-replacement-tail-wheel.html?wrh_pdp=7

**Comment by kaklik** [comment]
Vytištěný model je vyslicovaný hodně dutě a neobsahuje otvor pro čepičku ukončující drát kolečka. 

![image](https://user-images.githubusercontent.com/1194177/74840095-ac221980-5326-11ea-9aee-f72c5c5d85a8.png)

Tato čepička je v originálním dílu v úrovni trubky, aby nepřekážela výškovce.

![image](https://user-images.githubusercontent.com/1194177/74840733-c8728600-5327-11ea-9947-79b5550387cb.png)


![image](https://user-images.githubusercontent.com/1194177/74840775-d88a6580-5327-11ea-800e-a1ff887ca323.png)

**Comment by kaklik** [comment]
![image](https://user-images.githubusercontent.com/1194177/74859366-26629600-5347-11ea-9ee8-82b9d92f9f81.png)

**Comment by roman-dvorak** [comment]
Kostku drážku je potřeba o 3 mm zkátit. Dále by bylo vhodné trošku prodloužit část do tyče a zvětšit o trochu průměr o 0.2mm.
